// export * from './AlertConstants';
// export * from './UserConstants';
// export * from './JobTitleConstants';
// export * from './TaskTemplateConstants';
// export * from './DepartmentConstants';
// export * from './KPIUnitConstants';
// export * from './Err/ErrConstants';
// export * from './KPIMemberConstants';
// export * from './TaskManagementConstants';
// export * from './PerformTaskConstants';

export const kpiMemberConstants = {
    GETALL_KPIMEMBER_OfUNIT_REQUEST: 'GETALL_KPIMEMBER_OfUNIT_REQUEST',
    GETALL_KPIMEMBER_OfUNIT_SUCCESS: 'GETALL_KPIMEMBER_OfUNIT_SUCCESS',
    GETALL_KPIMEMBER_OfUNIT_FAILURE: 'GETALL_KPIMEMBER_OfUNIT_FAILURE',
    
    GETALL_KPIMEMBER_REQUEST: 'GETALL_KPIMEMBER_REQUEST',
    GETALL_KPIMEMBER_SUCCESS: 'GETALL_KPIMEMBER_SUCCESS',
    GETALL_KPIMEMBER_FAILURE: 'GETALL_KPIMEMBER_FAILURE',
    
    GETALL_KPIMEMBER_OFTASK_REQUEST: 'GETALL_KPIMEMBER_OFTASK_REQUEST',
    GETALL_KPIMEMBER_OFTASK_SUCCESS: 'GETALL_KPIMEMBER_OFTASK_SUCCESS',
    GETALL_KPIMEMBER_OFTASK_FAILURE: 'GETALL_KPIMEMBER_OFTASK_FAILURE',

    GET_KPIMEMBER_BYID_REQUEST: 'GET_KPIMEMBER_BYID_REQUEST',
    GET_KPIMEMBER_BYID_SUCCESS: 'GET_KPIMEMBER_BYID_SUCCESS',
    GET_KPIMEMBER_BYID_FAILURE: 'GET_KPIMEMBER_BYID_FAILURE',

    GET_KPIMEMBER_BYMONTH_REQUEST: 'GET_KPIMEMBER_BYMONTH_REQUEST',
    GET_KPIMEMBER_BYMONTH_SUCCESS: 'GET_KPIMEMBER_BYMONTH_SUCCESS',
    GET_KPIMEMBER_BYMONTH_FAILURE: 'GET_KPIMEMBER_BYMONTH_FAILURE',
    
    GETCURRENT_KPIMEMBER_REQUEST: 'GETCURRENT_KPIMEMBER_REQUEST',
    GETCURRENT_KPIMEMBER_SUCCESS: 'GETCURRENT_KPIMEMBER_SUCCESS',
    GETCURRENT_KPIMEMBER_FAILURE: 'GETCURRENT_KPIMEMBER_FAILURE',

    ADD_KPIMEMBER_REQUEST: 'ADD_KPIMEMBER_REQUEST',
    ADD_KPIMEMBER_SUCCESS: 'ADD_KPIMEMBER_SUCCESS',
    ADD_KPIMEMBER_FAILURE: 'ADD_KPIMEMBER_FAILURE',

    EDIT_KPIMEMBER_REQUEST: 'EDIT_KPIMEMBER_REQUEST',
    EDIT_KPIMEMBER_SUCCESS: 'EDIT_KPIMEMBER_SUCCESS',
    EDIT_KPIMEMBER_FAILURE: 'EDIT_KPIMEMBER_FAILURE',

    EDITSTATUS_KPIMEMBER_REQUEST: 'EDITSTATUS_KPIMEMBER_REQUEST',
    EDITSTATUS_KPIMEMBER_SUCCESS: 'EDITSTATUS_KPIMEMBER_SUCCESS',
    EDITSTATUS_KPIMEMBER_FAILURE: 'EDITSTATUS_KPIMEMBER_FAILURE',

    APPROVE_KPIMEMBER_REQUEST: 'APPROVE_KPIMEMBER_REQUEST',
    APPROVE_KPIMEMBER_SUCCESS: 'APPROVE_KPIMEMBER_SUCCESS',
    APPROVE_KPIMEMBER_FAILURE: 'APPROVE_KPIMEMBER_FAILURE',

    EVALUATETARGET_KPIMEMBER_REQUEST: 'EVALUATETARGET_KPIMEMBER_REQUEST',
    EVALUATETARGET_KPIMEMBER_SUCCESS: 'EVALUATETARGET_KPIMEMBER_SUCCESS',
    EVALUATETARGET_KPIMEMBER_FAILURE: 'EVALUATETARGET_KPIMEMBER_FAILURE',

    DELETE_KPIMEMBER_REQUEST: 'DELETE_KPIMEMBER_REQUEST',
    DELETE_KPIMEMBER_SUCCESS: 'DELETE_KPIMEMBER_SUCCESS',
    DELETE_KPIMEMBER_FAILURE: 'DELETE_KPIMEMBER_FAILURE',

    ADDTARGET_KPIMEMBER_REQUEST: 'ADDTARGET_KPIMEMBER_REQUEST',
    ADDTARGET_KPIMEMBER_SUCCESS: 'ADDTARGET_KPIMEMBER_SUCCESS',
    ADDTARGET_KPIMEMBER_FAILURE: 'ADDTARGET_KPIMEMBER_FAILURE',

    EDITTARGET_KPIMEMBER_REQUEST: 'EDITTARGET_KPIMEMBER_REQUEST',
    EDITTARGET_KPIMEMBER_SUCCESS: 'EDITTARGET_KPIMEMBER_SUCCESS',
    EDITTARGET_KPIMEMBER_FAILURE: 'EDITTARGET_KPIMEMBER_FAILURE',

    EDITSTATUS_TARGET_KPIMEMBER_REQUEST: 'EDITSTATUS_TARGET_KPIMEMBER_REQUEST',
    EDITSTATUS_TARGET_KPIMEMBER_SUCCESS: 'EDITSTATUS_TARGET_KPIMEMBER_SUCCESS',
    EDITSTATUS_TARGET_KPIMEMBER_FAILURE: 'EDITSTATUS_TARGET_KPIMEMBER_FAILURE',

    DELETETARGET_KPIMEMBER_REQUEST: 'DELETETARGET_KPIMEMBER_REQUEST',
    DELETETARGET_KPIMEMBER_SUCCESS: 'DELETETARGET_KPIMEMBER_SUCCESS',
    DELETETARGET_KPIMEMBER_FAILURE: 'DELETETARGET_KPIMEMBER_FAILURE',
};

export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    CURRENT_USER_EDIT: 'CURRENT_USER_EDIT',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE'
};